# Generated by Django 5.2 on 2025-06-13 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_subject_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='assigned_class',
        ),
    ]
