# Generated by Django 5.2 on 2025-06-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_subject_assigned_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_strength',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
