# Generated by Django 5.2 on 2025-06-26 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_course_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.academicyear')),
            ],
            options={
                'unique_together': {('academic_year', 'class_level')},
            },
        ),
    ]
