# Generated by Django 5.2 on 2025-06-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
    name='course',
    unique_together=set(),
)
    ]
