# Generated by Django 5.2 on 2025-06-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_drop_year_class_unique'),
    ]

    operations = [
         migrations.RunSQL(
            "DROP INDEX IF EXISTS adminapp_course_academic_year_id_class_level_uniq;",  # Replace with actual index name if different
            reverse_sql="",
        ),
    ]
