# Generated by Django 5.2 on 2025-06-26 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_drop_year_class_unique'),
        ('teacherapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1️⃣  Add the new field first
        migrations.AddField(
            model_name='student',           # or 'newstudent'
            name='class_group',
            field=models.ForeignKey(
                to='adminapp.classgroup',
                null=True, blank=True,
                on_delete=django.db.models.deletion.CASCADE,
            ),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(
                to=settings.AUTH_USER_MODEL,
                null=True, blank=True,
                on_delete=django.db.models.deletion.CASCADE,
            ),
        ),
        # 🗑️  (RemoveField for 'course' deleted, since field is already gone)

        # 2️⃣  Now add the unique-together constraint
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('class_group', 'roll_number')},
        ),
    ]
