# Generated by Django 5.2 on 2025-06-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0003_remove_student_course_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
