# Generated by Django 5.2 on 2025-06-27 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0005_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
