# Generated by Django 5.2 on 2025-06-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_drop_year_class_unique'),
        ('teacherapp', '0007_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('S1', 'Series 1'), ('S2', 'Series 2'), ('S3', 'Series 3'), ('I1', 'Internal 1'), ('I2', 'Internal 2'), ('I3', 'Internal 3')], max_length=2)),
                ('class_level', models.PositiveSmallIntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('mark', models.PositiveSmallIntegerField()),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherapp.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.subject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'exam_type', 'academic_year')},
            },
        ),
    ]
