# Generated by Django 5.2 on 2025-06-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0008_mark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
